# Generated by Django 3.0.2 on 2020-02-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_gift',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
