# Generated by Django 3.0.2 on 2020-02-19 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200218_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.CharField(choices=[('1', 'Gold'), ('2', 'Silver'), ('3', 'Bronz')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='social',
            name='social_id',
            field=models.CharField(max_length=20),
        ),
    ]
