# Generated by Django 3.0.2 on 2020-03-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200302_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('0', 'Male'), ('1', 'Famale')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_gift',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
