# Generated by Django 3.0.2 on 2020-02-20 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200220_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='folloing_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='follower_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='score',
        ),
        migrations.AlterField(
            model_name='commentuser',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_give_comment', to='account.Profile'),
        ),
        migrations.AlterField(
            model_name='commentuser',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_receive_comment', to='account.Profile'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='account.Profile'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='account.Profile'),
        ),
        migrations.AlterField(
            model_name='score',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='account.Profile'),
        ),
        migrations.AlterField(
            model_name='score',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_receiver', to='account.Profile'),
        ),
        migrations.AlterField(
            model_name='social',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile'),
        ),
    ]
