# Generated by Django 3.0.2 on 2020-02-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200220_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
