# Generated by Django 3.0.2 on 2020-02-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200220_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='score',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
