# Generated by Django 3.0.2 on 2020-02-20 22:06

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200220_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_cart',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[account.models.validate_size]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[account.models.validate_size]),
        ),
        migrations.AlterField(
            model_name='social',
            name='title',
            field=models.CharField(choices=[('0', 'Facebook'), ('1', 'Instagram'), ('2', 'Twitter'), ('3', 'Linkdin')], max_length=10),
        ),
    ]
