# Generated by Django 3.0.2 on 2020-02-29 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Massage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mtype', models.CharField(choices=[('0', 'text'), ('1', 'picture'), ('2', 'voice')], max_length=3)),
                ('text', models.TextField()),
                ('chat_id', models.PositiveIntegerField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiver', to='account.User')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sender', to='account.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
