# Generated by Django 3.0.2 on 2020-02-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='massage',
            name='chat_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
