# Generated by Django 3.0.2 on 2020-01-30 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAds',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelAds',
            fields=[
                ('baseads_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertise.BaseAds')),
                ('departure_country_traveler', models.CharField(max_length=50, verbose_name='departure_country_traveler')),
                ('destination_country_traveler', models.CharField(max_length=50, verbose_name='destination_country_traveler')),
                ('date_of_travel', models.DateTimeField(verbose_name='date_of_travel')),
                ('empty_weight', models.IntegerField(verbose_name='empty_weight')),
                ('ticket_picture', models.FileField(upload_to='', verbose_name='ticket_picture')),
                ('place_of_get_packet_traveler', models.CharField(max_length=20, verbose_name='place_of_get_packet_traveler')),
                ('place_of_give_packet_traveler', models.CharField(max_length=20, verbose_name='place_of_give_packet_traveler')),
            ],
            bases=('advertise.baseads',),
        ),
        migrations.CreateModel(
            name='PacketAds',
            fields=[
                ('baseads_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertise.BaseAds')),
                ('origin_country_packet', models.CharField(max_length=50, verbose_name='origin_country_packet')),
                ('destination_country_packet', models.CharField(max_length=50, verbose_name='destination_country_packet')),
                ('origin_city', models.CharField(max_length=50, verbose_name='origin_city')),
                ('destination_city', models.CharField(max_length=50, verbose_name='destination_city')),
                ('categoty_of_packet', models.CharField(choices=[('doc', 'Document'), ('bok', 'Book')], max_length=20, verbose_name='categoty_of_packet')),
                ('weight_of_packet', models.PositiveIntegerField(verbose_name='weight_of_packet')),
                ('dimension_of_packet', models.PositiveIntegerField(verbose_name='dimension_of_packet')),
                ('suggested_price', models.PositiveIntegerField(verbose_name='suggested_price')),
                ('place_of_get_packet', models.CharField(max_length=20, verbose_name='place_of_get_packet')),
                ('place_of_give_packet', models.CharField(max_length=20, verbose_name='place_of_give_packet')),
                ('date_of_send_packet', models.DurationField(verbose_name='date_of_send_packet')),
                ('buy_by_traveler', models.BooleanField(verbose_name='buy_by_traveler')),
                ('qr_code', models.CharField(max_length=100, verbose_name='qr_code')),
                ('ads_visit_count', models.IntegerField(verbose_name='ads_visit_count')),
                ('status', models.CharField(choices=[('wfa', 'wait_for_approving'), ('p', 'Published'), ('wo', 'With_offer'), ('abu', 'accept_by_users'), ('s', 'sended')], max_length=3)),
                ('owner_of_packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_of_packet', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('advertise.baseads',),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('baseads_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertise.BaseAds')),
                ('offer_price', models.IntegerField(verbose_name='offer_price')),
                ('offer_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_by', to=settings.AUTH_USER_MODEL)),
                ('offer_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_to', to=settings.AUTH_USER_MODEL)),
                ('packet_ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packet_ads', to='advertise.PacketAds')),
                ('travel_ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_ads', to='advertise.TravelAds')),
            ],
            bases=('advertise.baseads',),
        ),
        migrations.CreateModel(
            name='AdsBookmark',
            fields=[
                ('baseads_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertise.BaseAds')),
                ('booked_ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_ads', to='advertise.PacketAds')),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_by', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('advertise.baseads',),
        ),
    ]
