# Generated by Django 3.0.2 on 2020-02-11 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoty', models.CharField(choices=[('0', 'مدارک'), ('1', 'کتاب'), ('2', 'لباس'), ('3', 'سایر موارد')], max_length=20)),
                ('weight', models.PositiveIntegerField()),
                ('weight_unit', models.CharField(choices=[('0', 'گرم'), ('1', 'کیلوگرم'), ('2', 'پوند')], max_length=5)),
                ('suggested_price', models.PositiveIntegerField()),
                ('currency_price', models.CharField(choices=[('0', 'دلار'), ('1', 'یورو'), ('2', 'ریال')], max_length=3, verbose_name='currency')),
                ('place_of_get', models.CharField(choices=[('0', 'فرودگاه'), ('1', 'درب منزل'), ('2', 'شهر')], max_length=20)),
                ('place_of_give', models.CharField(choices=[('0', 'فرودگاه'), ('1', 'درب منزل'), ('2', 'شهر')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('buy', models.BooleanField(verbose_name='buy availibity')),
                ('qr_code', models.ImageField(blank=True, upload_to='')),
                ('visit_count', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('0', 'در انتظار تایید'), ('1', 'منتشر شده'), ('2', 'دارای پیشنهاد'), ('3', 'پذیرش شده'), ('4', 'ارسال شده'), ('5', 'عدم تایید')], max_length=3)),
                ('picture', models.ImageField(blank=True, upload_to='')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_city', to='account.City')),
                ('destination_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_country', to='account.Country')),
                ('origin_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_city', to='account.City')),
                ('origin_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_country', to='account.Country')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packet_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(verbose_name='date')),
                ('airline', models.CharField(blank=True, choices=[('0', 'Mahan'), ('1', 'Iran Air'), ('2', 'Emirate'), ('3', 'Atlas Jet'), ('4', 'other')], max_length=40)),
                ('pic', models.FileField(blank=True, upload_to='')),
                ('is_approved', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empty_weight', models.PositiveIntegerField()),
                ('weight_unit', models.CharField(choices=[('0', 'گرم'), ('1', 'کیلوگرم'), ('2', 'پوند')], max_length=3)),
                ('place_of_get', models.CharField(choices=[('0', 'فرودگاه'), ('1', 'درب منزل'), ('2', 'شهر')], max_length=20)),
                ('place_of_give', models.CharField(choices=[('0', 'فرودگاه'), ('1', 'درب منزل'), ('2', 'شهر')], max_length=20)),
                ('status', models.CharField(choices=[('0', 'در انتظار تایید'), ('1', 'منتشر شده'), ('2', 'دارای پیشنهاد'), ('3', 'پذیرش شده'), ('4', 'ارسال شده'), ('5', 'عدم تایید')], max_length=3)),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depar_country', to='account.Country')),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depar_city', to='account.City')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dest_country', to='account.Country')),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dest_city', to='account.City')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traveler', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='advertise.Ticket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(choices=[('0', 'عدم رعایت صداقت'), ('1', ''), ('2', '')], max_length=3)),
                ('text', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to=settings.AUTH_USER_MODEL)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertise.Packet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.PositiveIntegerField()),
                ('currency', models.CharField(choices=[('0', 'دلار'), ('1', 'یورو'), ('2', 'ریال')], max_length=3)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packet_ads', to='advertise.Packet')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travel_ads', to='advertise.Travel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advertise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advertise', to='advertise.Packet')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owner_bookmark', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
